apiVersion: v1
kind: Pod
metadata:
  name: kiada-sn-pod
  # labels:
  #   env: test
spec:
  containers:
  - name: kiada-sn-cont
    image: luksa/kiada:0.1
    imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: r2lab/node
                operator: NotIn
                values: [ "true" ]
