apiVersion: v1
kind: Pod
metadata:
  name: kiada-r2lab-pod
spec:
  containers:
  - name: kiada-r2lab-cont
    image: luksa/kiada:0.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    r2lab/node: "true"
