# warning: this requires the r2lab nodes to be labeled
# with fit-label-nodes which is otherwise no longer needed
apiVersion: v1
kind: Pod
metadata:
  name: kiada-sopnode-pod
spec:
  containers:
  - name: kiada-sopnode-cont
    image: luksa/kiada:0.1
    imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: r2lab/node
                operator: NotIn
                values: [ "true" ]
