# warning: this requires the r2lab nodes to be labeled
# with fit-label-nodes which is otherwise no longer needed
apiVersion: v1
kind: Pod
metadata:
  name: kiada-r2lab-pod 
spec:
  containers:
  - name: kiada-r2lab-cont
    image: luksa/kiada:0.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    r2lab/node: "true"
