apiVersion: v1
kind: Pod
metadata:
  name: kiada-r2-pod
  # labels:
  #   env: test
spec:
  containers:
  - name: kiada-r2-cont
    image: luksa/kiada:0.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    r2lab/node: "true"
