# a piece of config targetting the apiserver
# this gets injected into
# /etc/kubernetes/manifests/kube-apiserver.yaml
# by kube-install.sh using yq and the companion
# yq script named identically

spec:
  containers:
    volumeMounts:
    - name: konnectivity-uds
      mountPath: /etc/kubernetes/konnectivity-server
      readOnly: false
  volumes:
  - name: konnectivity-uds
    hostPath:
      path: /etc/kubernetes/konnectivity-server
      type: DirectoryOrCreate
